Fix: #347 : Improve RingBuffer
GoogleChromeLabs/web-audio-samples pull request #352
Opened 2024-02-25 11:41 UTC by Daksh-10

In https://github.com/GoogleChromeLabs/web-audio-samples/issues/347 ,
I updated the index directly instead of making a new temporary every iteration, which removes the inefficiency.

2024-02-27 23:38 UTC, mjwilson-google requested changes
Thank you for working on this!  Please address the comments in the code.  It would also be good to run src/audio-worklet/design-pattern/wasm-ring-buffer/main.js before and after the change and verify that this change doesn't affect the behavior.

2024-02-27 23:38 UTC, mjwilson-google commented on src/audio-worklet/design-pattern/lib/wasm-audio-helper.js
> +      this._writeIndex = (this._writeIndex + i) % this._length;
We should just be incrementing `this._writeIndex` by `1` each iteration now.

2024-02-27 23:38 UTC, mjwilson-google commented on src/audio-worklet/design-pattern/lib/wasm-audio-helper.js
> +      this._readIndex = (this._readIndex + i) % this._length;
Same as above, we should just be incrementing by `1` instead of `i` now that we're storing back to the class variable.

2024-03-03 12:16 UTC, Daksh-10 commented
@mjwilson-google,
 I corrected the changes.

2024-03-04 23:42 UTC, mjwilson-google commented on src/audio-worklet/design-pattern/lib/wasm-audio-helper.js
> +      //updating index directly instead of making new temporary every iteration
I don't think this comment is necessary.

2024-03-04 23:43 UTC, mjwilson-google commented on src/audio-worklet/design-pattern/lib/wasm-audio-helper.js
> +      //updating index directly instead of making new temporary every iteration
Same here, since the old line is being removed the context for the comment is lost.  We can just make the change without adding this comment.

2024-03-07 10:21 UTC, mjwilson-google requested changes
Thanks for updating.  I missed this in the initial review, but we need to increment the indexes after using them now, not before.  Once we do this I think everything should be good!

2024-03-07 14:08 UTC, Daksh-10 commented
I think we took time to correct the issue, but I guess it is working correctly now.

2024-03-07 18:18 UTC, mjwilson-google approved these changes

2024-03-07 19:11 UTC, merged