Added stop button for hello audio worklet example
GoogleChromeLabs/web-audio-samples pull request #387
Opened 2024-07-23 04:18 UTC by duojet2ez

I added a stop button to the hello audio worklet example enabling the user to stop and start the sound. 

Specifically, I used audioContext.suspend() to allow the user to pause the sound with a stop button. And I added an isModuleLoaded check to avoid redundantly calling addModule. Also added isPlaying to toggle the playing state.

2024-07-23 16:54 UTC, duojet2ez commented
@hoch this is the single example version of my previous PR. Just to update you on getting a test page for quick and easy inspection of the PR, I started looking into this again yesterday and it does seem possible to do with github pages + github actions. I will continue researching this over the course of the week and provide updates.

2024-07-23 19:59 UTC, hoch requested changes
Thanks for your patience, and I am hopeful that we can land this pretty soon.

2024-07-23 19:59 UTC, hoch commented on src/audio-worklet/basic/hello-audio-worklet/main.js
> +    oscillatorNode.start();
I think L13~L16 can be extracted to a different method.

`isModuleLoaded` should guard around the `addModule` method, nothing else.

2024-07-23 19:59 UTC, hoch commented on src/audio-worklet/basic/hello-audio-worklet/main.js
> +      await startAudio(audioContext);
You can call `audioContext.resume()` here.

2024-07-23 19:59 UTC, hoch commented on src/audio-worklet/basic/hello-audio-worklet/main.js
> +  } else context.resume();
To make the logic clear, please keep this call within the user interaction callback (`click`) below.

2024-07-23 19:59 UTC, hoch commented on src/audio-worklet/basic/hello-audio-worklet/main.js
> +let isModuleLoaded = false;
You will probably need two different booleans:

`isModuleLoaded`: to guard `addModule()` call.
`isGraphReady`: to guard the node construction/connection logic.

Then the actual `click` event will only care about the context's `resume()` and `suspend()` call.

I believe this is the most efficient way.

2024-07-23 19:59 UTC, hoch commented on src/audio-worklet/basic/hello-audio-worklet/main.js
> +  buttonEl.addEventListener('mouseenter', () => {
I believe L41~L51 is not necessary. Hovering action is not visible on the mobile platform either.

2024-07-27 05:01 UTC, duojet2ez commented
Thanks for the feedback!! 

- I extracted the following lines mentioned and put them in a loadGraph function:

  oscillatorNode = new OscillatorNode(context);
  const bypasser = new AudioWorkletNode(context, 'bypass-processor');
  oscillatorNode.connect(bypasser).connect(context.destination);
  oscillatorNode.start();

- created a bool isGraphReady to serve as a guard for graph connections in startAudio function
- removed unnecessary lines 41-51
- audioContext.resume() placed in click event 
- Click event should now only care about resume and suspend

2024-07-29 16:35 UTC, hoch approved these changes
LGTM

It looks like there's a conflict, so once you resolve it I'll merge the PR.

2024-07-30 00:33 UTC, duojet2ez commented
Cool I think that should resolve the conflict!

2024-07-30 16:53 UTC, merged