Added Linting as a part of CI
GoogleChromeLabs/web-audio-samples pull request #393
Opened 2024-08-23 14:48 UTC by tarunsinghofficial

## Overview
This PR introduces automated linting to our Continuous Integration (CI) pipeline using GitHub Actions. It aims to ensure consistent code style and catch potential errors early in the development process.

## Changes
- Added a new GitHub Actions workflow file: `.github/workflows/ci.yml`
- Configured the workflow to run on push to main/master branches and on pull requests
- Added a `.prettierignore` to ignore some package managers
- Implemented Prettier and ESLint checks for all files
- Added specific checks for changed files in pull requests

## Implementation Details
The new CI workflow does the following:
1. Check out the code
2. Sets up Node.js
3. Installs dependencies
4. Runs Prettier on all files
5. Runs ESLint on all files
6. For pull requests, run Prettier and ESLint on changed files only

## Notes
- Caching of npm artifacts was considered but not implemented. We can add this later if build times become an issue.
- The workflow is configured to use Node.js version 18. We may need to update this in the future.

Please review and let me know if any changes or additions are needed.

2024-10-05 14:25 UTC, tarunsinghofficial commented
hi @hoch. Any update on this?

2024-10-28 13:48 UTC, tarunsinghofficial commented
hi @hoch. Any update on this?

2024-11-29 07:06 UTC, tarunsinghofficial commented
Hi @hoch, Any update on this PR?

2024-11-29 18:58 UTC, hoch commented
Apologies. I am currently swamped by urgent tasks at work. I'll ask around if other team members are able to review this change.

2025-01-02 19:20 UTC, mjwilson-google requested changes
Hi @tarunsinghofficial, thank you for raising and working on this issue.  I'll take on the review since Hongchan has been overloaded recently.

The overall approach looks good to me.  I left some comments, please take a look and let me know what you think.

2025-01-02 19:20 UTC, mjwilson-google commented on .prettierrc.json
> +      "files": "*.njk",
I think the way things are written now the CI won't pass .njk files to prettier; am I missing something?

2025-01-02 19:20 UTC, mjwilson-google commented on .prettierrc.json
> +  "useTabs": true,
Please set "useTabs" to `false` (https://google.github.io/styleguide/tsguide.html#whitespace-characters)

2025-01-02 19:20 UTC, mjwilson-google commented on .prettierrc.json
> +  "overrides": [
According to https://prettier.io/docs/en/options.html#parser we shouldn't necessarily have to set the parser explicitly (I'm not sure why it was specified before).  Do you think we could just remove the "overrides" section?

2025-01-02 19:20 UTC, mjwilson-google commented on package.json
> +    "lint:prettier": "prettier --check src/**/*.js src/**/*.html",
If we remove the "Lint changed files" step we may want to add the other relevant filetypes here.

2025-01-04 09:01 UTC, tarunsinghofficial commented on .github/workflows/ci.yml
> +    branches: [ main, master ]
Yeah, sure. Removed the master entry from the file.

2025-01-04 09:01 UTC, tarunsinghofficial commented on .github/workflows/ci.yml
> +    branches: [ main, master ]
Done here too.

2025-01-04 09:05 UTC, tarunsinghofficial commented on .github/workflows/ci.yml
> +      - name: Lint changed files
Yes, we can just run linting on the changed files, so that there is no redundancy.

2025-01-04 09:11 UTC, tarunsinghofficial commented on .prettierignore
> +# Package Managers
Removed unnecessary exclusions since they're already excluded by other parts of the config.

2025-01-04 09:11 UTC, tarunsinghofficial commented on .prettierrc.json
> +  "useTabs": true,
Done

2025-01-04 09:12 UTC, tarunsinghofficial commented on .prettierrc.json
> +      "files": "*.njk",
Removed the .njk parser override that was causing issues with .njk files.

2025-01-04 09:23 UTC, tarunsinghofficial commented on .prettierrc.json
> +  "overrides": [
Yes, It's unnecessary to include the overrides section. Removed the overrides section to make it more flexible and cleaner.

2025-01-04 09:25 UTC, tarunsinghofficial commented on package.json
> +    "lint:prettier": "prettier --check src/**/*.js src/**/*.html",
I decided to keep the "Lint changed files" step, which runs linters only on the changed files. As a result, there's no need to modify the package.json file to include additional file types for linting, since the dynamic filtering for relevant files is handled in the "Lint changed files" step itself.

2025-01-05 20:15 UTC, mjwilson-google requested changes
Thank you, looking even better!  Just a few more comments.

2025-01-05 20:15 UTC, mjwilson-google commented on .github/workflows/ci.yml
> +      - name: Lint changed files
Can we remove the "Run Prettier" step above too?

2025-01-05 20:15 UTC, mjwilson-google commented on .prettierignore
> +# Package Managers
Can we remove this entire file now?

2025-01-05 20:15 UTC, mjwilson-google commented on package.json
> +    "lint:prettier": "prettier --check src/**/*.js src/**/*.html",
Can we remove the "lint:prettier" and "lint:eslint" lines now too?

2025-01-05 20:15 UTC, mjwilson-google commented on .github/workflows/ci.yml
> +        if: github.event_name == 'pull_request'
Since this step does the actual linting, and it only runs on 'pull_request', we should probably do one of the following:
- Either remove the `push` line from the `on` section at the top of the file
- Or, allow this linting to run on both push and pull request

What do you think?

2025-01-06 09:00 UTC, tarunsinghofficial commented on package.json
> +    "lint:prettier": "prettier --check src/**/*.js src/**/*.html",
Yes, removed both "lint:prettier" and "lint:eslint" from `packagejson`

2025-01-06 09:01 UTC, tarunsinghofficial commented on .prettierignore
> +# Package Managers
Removed the `.prettierignore` file.

2025-01-06 09:02 UTC, tarunsinghofficial commented on .github/workflows/ci.yml
> +      - name: Lint changed files
Removed the unnecessary "Run Prettier" step.

2025-01-06 09:05 UTC, tarunsinghofficial commented on .github/workflows/ci.yml
> +        if: github.event_name == 'pull_request'
Thanks for pointing this out! After reviewing, I agree that having the push trigger doesn't make much sense here since this step is focused on linting for pull requests. I'll update the workflow to remove the push line from the on section, ensuring that this workflow only runs on pull requests.

2025-01-06 09:09 UTC, tarunsinghofficial commented
Thanks for the feedback @mjwilson-google. Done with all the changes and is ready to 🚀 :)

2025-01-06 16:02 UTC, mjwilson-google approved these changes
Looks good to me!  Thank you for your work on this.

2025-01-06 16:08 UTC, merged